import { For, createUniqueId } from 'solid-js';

import { cn } from '../utils';

export interface FaqItem {
  question: string;
  answer: string;
}


export interface FaqAccordionProps {
  items: FaqItem[];
  /**
   * Only one answer open at a time (native `<details name>` grouping).
   * Defaults to `true`; browsers without support simply allow several.
   */
  exclusive?: boolean;
  /** Group name used for `exclusive`. A unique id is generated by default. */
  name?: string;
  class?: string;
}

/**
 * Stack of collapsible questions built on native `<details>` / `<summary>`.
 * Works without any client-side JavaScript, so it can be server-rendered
 * without a hydration directive and is keyboard / screen-reader friendly.
 */
export function FaqAccordion(props: FaqAccordionProps) {
  const generatedName = createUniqueId();
  const groupName = () => props.name ?? generatedName;
  // Spread so the `name` attribute isn't rejected by Solid's `details` typings.
  const group = () => (props.exclusive === false ? {} : { name: groupName() });

  return (
    <div class={cn('flex flex-col gap-2', props.class)}>
      <For each={props.items}>
        {(item) => (
          <details
            {...group()}
            class='group rounded-lg border border-brand-hairline bg-surface'
          >
            <summary
              class={cn(
                'flex cursor-pointer list-none items-center justify-between gap-4',
                'rounded-lg px-4 py-2.5 md:py-1.75',
                'text-card-cta leading-120 text-ink-muted',
                'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand',
                '[&::-webkit-details-marker]:hidden'
              )}
            >
              <span>{item.question}</span>
              <svg
                aria-hidden='true'
                viewBox='0 0 12 12'
                class='size-3 shrink-0 text-ink-muted transition-transform duration-200 group-open:rotate-180'
              >
                <path
                  d='M2 4.25 6 8l4-3.75'
                  fill='none'
                  stroke='currentColor'
                  stroke-width='1.6'
                  stroke-linecap='round'
                  stroke-linejoin='round'
                />
              </svg>
            </summary>
            <div class='px-4 pt-1 pb-3.5 text-card-tag-md leading-126 text-ink-muted'>
              {item.answer}
            </div>
          </details>
        )}
      </For>
    </div>
  );
}
