import { cva, type VariantProps } from 'class-variance-authority';
import type { Component } from 'solid-js';
import { Dynamic } from 'solid-js/web';

const featureCardVariants = cva('flex w-full items-center rounded-3xl border transition-shadow duration-200',{variants:{variant:{default:'border-border bg-surface',muted:'border-border bg-surface-muted',accent:'border-surface-accent-strong bg-surface-accent',inverse:'border-accent bg-accent text-accent-foreground',purple:'border-badge-purple-background bg-badge-purple-background',orange:'border-badge-orange-background bg-badge-orange-background',green:'border-badge-green-background bg-badge-green-background',blue:'border-badge-blue-background bg-badge-blue-background',neutral:'border-badge-neutral-background bg-badge-neutral-background'},size:{sm:'gap-3 px-4 py-3',md:'gap-4 px-5 py-4',lg:'gap-5 px-6 py-5'},effect:{none:'',lift:'hover:-translate-y-1 hover:shadow-lg',glow:'hover:shadow-md hover:shadow-primary/25'}},defaultVariants:{variant:'default',size:'md',effect:'none'}});
const text = cva('text-foreground',{variants:{variant:{default:'text-foreground',muted:'text-foreground',accent:'text-foreground',inverse:'text-accent-foreground',purple:'text-badge-purple-foreground',orange:'text-badge-orange-foreground',green:'text-badge-green-foreground',blue:'text-badge-blue-foreground',neutral:'text-badge-neutral-foreground'}},defaultVariants:{variant:'default'}});
const iconBox = cva('flex shrink-0 items-center justify-center rounded-2xl',{variants:{variant:{default:'bg-surface-muted text-foreground',muted:'bg-surface text-foreground',accent:'bg-surface-accent-strong text-primary',inverse:'bg-accent-foreground/20 text-accent-foreground',purple:'bg-badge-purple-foreground/15 text-badge-purple-foreground',orange:'bg-badge-orange-foreground/15 text-badge-orange-foreground',green:'bg-badge-green-foreground/15 text-badge-green-foreground',blue:'bg-badge-blue-foreground/15 text-badge-blue-foreground',neutral:'bg-badge-neutral-foreground/15 text-badge-neutral-foreground'},size:{sm:'size-10',md:'size-14',lg:'size-16'}},defaultVariants:{variant:'default',size:'md'}});
export interface Props extends VariantProps<typeof featureCardVariants>{title:string;subtitle:string;icon:Component<any>;class?:string}
export default function FeatureCard(props:Props){const size=()=>props.size??'md';const variant=()=>props.variant??'default';return <div class={`${featureCardVariants({variant:variant(),size:size(),effect:props.effect})} ${props.class??''}`}><div class={iconBox({variant:variant(),size:size()})}><Dynamic component={props.icon} class={size()==='sm'?'size-5':size()==='md'?'size-7':'size-8'}/></div><div class='flex min-w-0 flex-col justify-center'><h4 class={`leading-normal font-semibold ${size()==='sm'?'text-base':size()==='md'?'text-xl':'text-2xl'} ${text({variant:variant()})}`}>{props.title}</h4><p class={`mt-1 leading-normal opacity-80 ${size()==='sm'?'text-xs':size()==='md'?'text-base':'text-lg'} ${text({variant:variant()})}`}>{props.subtitle}</p></div></div>}
